### PR TITLE
Binomial Calibration

### PR DESCRIPTION
**Pull request by byoungman**
New stuff...
1. I've updated the calibration analysis a bit.
2. I've separated the data collation, and put a separate bullet for it on the vignette markdown index, which has hopefully been done okay.
3. Some new data added.

### CODE REVIEW

**Review by BayesExeter — COMMENTED** [review]
This looks safe to merge to me looking at the diffs. What I can't do is view the website to see if the changes worked, so want Stefan to comment or take a look. Stefan, how can I view the website that would appear on Ben's fork of the master? That will help me merge straight forward pulls like this.

**Comment by sieste** [comment]
@BayesExeter Not sure if this is the best way to preview the vignette, but it works: When you click on the link [Binomal calibration](https://github.com/UQ4covid/uq4covid.github.io/pull/5/commits/c3be53203b9e81fd58315fd6c6fbd580c5af2dea) above you are taken to the commit summary. Scroll down to the new html file `vignettes/BinomialCalibration.html`. In the dotdotdot menu next to it there is a link to view the file. Copy the link url and paste it into [htmlpreview.github.io](https://htmlpreview.github.io/) to preview the vignette.

**Comment by BayesExeter** [comment]
> @BayesExeter Not sure if this is the best way to preview the vignette, but it works: When you click on the link [Binomal calibration](https://github.com/UQ4covid/uq4covid.github.io/pull/5/commits/c3be53203b9e81fd58315fd6c6fbd580c5af2dea) above you are taken to the commit summary. Scroll down to the new html file `vignettes/BinomialCalibration.html`. In the dotdotdot menu next to it there is a link to view the file. Copy the link url and paste it into [htmlpreview.github.io](https://htmlpreview.github.io/) to preview the vignette.

But that's not going to let me see if the site works (like if the link in the vignettes.md works). It's really useful to look at the vignette though :)

**Comment by sieste** [comment]
Ah, ok. I don't know how to view Ben's entire version of the website. I'll do some research and get back. I also think it's safe to merge, so please go ahead.

**Comment by sieste** [comment]
It looks like the only way to preview everything is to pull the commit into your machine, and preview the site with a local jekyll instance running on your machine. Provided you have jekyll installed you simply run "jekyll serve" somewhere in the repository and then can view the page on 127.0.0.1:4000 in your browser.

**Pull request merged**
