### PR TITLE
Adding QK emulation initial experiment vignette. More needs to be done

### PR DESCRIPTION
**Pull request by EvanBaker57**
Just adding my initial Quantile kriging test markdown. 
I think I did everything right following https://uq4covid.github.io/vignettes/guide-to-posting-vignettes
But I'm not super familiar with github or markdown, so not certain

### CODE REVIEW

**Review by BayesExeter — CHANGES_REQUESTED** [review]
Hi Evan,

It mainly looks good. Could you remove the .Rhistory unless it is necessary. I will then approve and merge

**Review by BayesExeter — CHANGES_REQUESTED** [review]
Also, Just noticed there is a html rendering of vignettes here too. Could you delete that? I can do that I think, if it's an accident.

**Comment by EvanBaker57** [comment]
Thinks thats done now?

**Review by BayesExeter — APPROVED** [review]
Thanks Evan. Looks good. I'll test website on merge but I can't see any errors.

**Pull request merged**
