### PR TITLE
New model

### PR DESCRIPTION
**Pull request by tjmckinley**

### CODE REVIEW

**Comment by BayesExeter** [comment]
I am going to merge this without checking it out etc first because this PR is essentially the start of the UQ4Covid project. We're going with it!

**Comment by tjmckinley** [comment]
This shouldn't have changed anything in any folder other the vignette I'm responsible for.

**Comment by BayesExeter** [comment]
Surely the website changes now?

**Comment by BayesExeter** [comment]
As in, there is a place for this new model separate from the old? I'll take a look, but anyway the PR is approved and we can always amend the site later.

**Comment by tjmckinley** [comment]
There isn't a separation between the old model and this one, because it's an ongoing development. However, I could extract the old model vignette as a separate link on the website if required easily enough.

The website has been updated as far as I can see.

**Pull request merged**
