### PR TITLE
Merge vignette

### PR DESCRIPTION
**Pull request by tjmckinley**
Combined Danny and my vignettes. Added custom CSS.

### CODE REVIEW

**Review by BayesExeter — CHANGES_REQUESTED** [review]
I would like to keep the separate running your own link maybe. We can always remove it later. Like you said somewhere, if you want the running for dummies link side by side with the model, that doesn't look feasible with only this option.

**Comment by tjmckinley** [comment]
How about this. I've kept a single link in the main page, because I think it's useful to keep the run for dummies and model structure kept together. However, everything is now a separate file, so you can have the links open side-by-side.

**Review by BayesExeter — COMMENTED** [review]
Hmmm. You would have to open the separate ones on a html viewer or download though as they won't be available on the website. Furthermore, annoyingly there is no link from the website back to the gitpage, so if you were on the website, you wouldn't know that it was there to view. Worth linking from the vignette?

**Comment by tjmckinley** [comment]
Now set up all links on the front page.

**Review by BayesExeter — APPROVED** [review]

**Pull request merged**
