### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by tjmckinley**
Attempt to move incidence calculations into the extractor, and thus simplify the model code and documentation.

### CODE REVIEW

**Review by BayesExeter — COMMENTED** [review]
With the new incidence etc, should I actually try to redo the Metawards tests? I don't really have time and as there are no conflicts with the master, it's probably fine. I'm inclined to just approve and test Scotland, which is the key next step.

**Comment by tjmckinley** [comment]
Yes, ideally. I realised I haven't updated your user guide, but I have updated the more detailed version, which you could borrow from. Ideally we would want MetaWards 1.2.0 to be released so that we can install without having to install from source (although Christopher did send me a binary if needed).

We really need to check Chris F is happy with me butchering his extractor. I'd be tempted to leave it as a PR until we decide whether to go with it or not.

**Comment by BayesExeter** [comment]
I noticed from your last email that this one is contingent on another piece of software being released from someone else, so let's hang back and wait for MW1.2.

**Comment by tjmckinley** [comment]
Yes, and also let's wait on Chris F.

**Comment by fentonscode** [comment]
With the current time-pressure just merge, I am going to have to redesign the extractors to cope with the new calculations anyway, so being able to pull this makes things easier

**Review by BayesExeter — APPROVED** [review]
Since we've run a massive ensemble, in for a penny :P

**Comment by fentonscode** [comment]
Can anyone merge? I don't have permission on this repo

**Comment by BayesExeter** [comment]
> Can anyone merge? I don't have permission on this repo

it is merged

**Comment by fentonscode** [comment]
So it is, I thought people were still waiting for each other. No worries!

**Pull request merged**
