### PR TITLE
New extractor

### PR DESCRIPTION
**Pull request by tjmckinley**
This is updated documentation etc. that uses Chris' new extractor.

@fentonscode  I made a few minor changes to the extractor. Firstly I renamed it "ward_extractor.py" so it simply replaces the other one. Secondly I changed the name of the output files to "stages.db.bz2" (and not "stages3.db.bz2") for consistency/ease. Thirdly, I amended your "TODO" comment to clarify the amalgamation (it's not quite deltas). I hope this is OK.

### CODE REVIEW

**Review by fentonscode — APPROVED** [review]
@tjmckinley Happy with the changes, there's a few odd variable names in my extractor still hanging around, but it's likely to change slightly again when we go to ISCA and use networked database writes

**Comment by tjmckinley** [comment]
Thanks Chris, I was going to change those also, but thought it best to leave them in case I missed one somewhere!

**Comment by tjmckinley** [comment]
I was also chatting to Leon and he's quite keen that we try to simplify the mover and reconstruct the incidence in the extractor. This is not something that we need to do straight away, since it won't change the inputs or model at all, but I'll have a think about how to do it. It should be a line or two extra in the mover, but then means we can remove all the "X1"-type classes.

**Comment by fentonscode** [comment]
This depends on what adjustments have been / need to be made to the MetaWards codebase - I will have a think about a reorganisation of everything so that we can present our movers, mixers, iterators and extractors to the developers to confirm we are after the same thing. P.S.: I don't have merge permissions here, it might only be Stefan?

**Comment by tjmckinley** [comment]
I think the idea is that nothing needs to change in MetaWards. We should be able to simplify the mover and put some extra parts in the extractor. Don't worry about this, I'll have a play and if I come up with anything worthwhile we can chat then. I think Danny has merge rights!

**Review by BayesExeter — APPROVED** [review]

**Pull request merged**
